bot:
    db_url: 'mongodb://localhost:27017/'
    db_name: 'project_timeless'
    # Resolution supports either '2560x1440' or '1920x1080'
    resolution: '2560x1440'
    # breaks_per_full_inventory specifies how many ~5 min breaks to take per
    # full inventory of jewels
    breaks_per_full_inventory: 0
    initial_sleep: 3
    exit_hotkey: 'f4'
    # If accept_trades is set to True, the bot will try to receive jewels
    # from other players through trade, analyze them and return them.
    accept_trades: False
input_handler:
    key_press_interval: 200 # millseconds
    mouse_click_interval: 200 # millseconds
# The trader section is only needed to be set if you want to use the
# trading functionality.
trader:
    # if accept_trades is set to True, this message will cause the bot to
    # invite the sending player
    invite_message: 'inv'
    # The log path needs to point to the Client.txt logfile in order to
    # find the whispers and other events happening in the chat
    # This is only needed if the accept_trades is set to True
    log_path: 'C:\Program Files (x86)\Grinding Gear Games\Path of Exile\logs\Client.txt'
tree_nav:
    # How many CPU processes to use for the OCR
    ocr_threads: 8
    # Divides the sleep timer of node search. Higher value = faster analyzing.
    # Could cause issues if set higher.
    node_search_speed_factor: 3
mod_search_site:
    db_url: 'mongodb://localhost:27017/'
    db_name: 'project_timeless'
    # The number of jewels to return in a search
    jewels_per_search: 50
    # The number of mods to show when listing the latest jewel additions to
    # the database. The mods shown when looking at the latest additions are the
    # mods that deviate the most from the mean of that mod.
    n_notable_mods_to_display: 3
